<?xml version="1.0" encoding="utf-8"?><Database Name="OttJohnData" Class="GenericMembershipDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=.;Initial Catalog=OttJohnData;User ID=sa;Password=3Pitters@3" Provider="System.Data.SqlClient" />
  <Function Name="dbo.InsertUserInformation" Method="InsertUserInformation">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MemberEmail" Parameter="memberEmail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MemberUserId" Parameter="memberUserId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="MemberId" Parameter="memberId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExtendedUserInformation" Method="GetExtendedUserInformation">
    <ElementType Name="GetExtendedUserInformationResult">
      <Column Name="MemberUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserInAppsAndRoles" Method="GetUserInAppsAndRoles">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetUserInAppsAndRolesResult">
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeletemMembershipInformation" Method="DeletemMembershipInformation">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_GetRolesForUser" Method="aspnet_UsersInRoles_GetRolesForUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_UsersInRoles_GetRolesForUserResult">
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChangeMemberEmail" Method="ChangeMemberEmail">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NewEmail" Parameter="newEmail" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCricketUserTable" Method="UpdateCricketUserTable">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MemberUserId" Parameter="memberUserId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllUnapprovedMembers" Method="GetAllUnapprovedMembers1">
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="GetAllUnapprovedMembersResult1">
      <Column Name="rowNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MemberUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetExtMemberDetails" Method="GetExtMemberDetails">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetExtMemberDetailsResult">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetFeatureTreeGroups" Method="GetFeatureTreeGroups">
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetFeatureTreeGroupsResult">
      <Column Name="GroupNameId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserInAppsAndRolesNew" Method="GetUserInAppsAndRolesNew">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetUserInAppsAndRolesNewResult">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetApplicationName" Method="GetApplicationName">
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="UserInApp" Parameter="userInApp" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckCricketConnection" Method="CheckCricketConnection">
    <Parameter Name="RetVal" Parameter="retVal" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetApplicationNames" Method="GetApplicationNames">
    <ElementType Name="GetApplicationNamesResult">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserInRolesForApp" Method="GetUserInRolesForApp">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetUserInRolesForAppResult">
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="UserInRole" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdatePaydayUserTable" Method="UpdatePaydayUserTable">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MemberUserId" Parameter="memberUserId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetCurrentCricketEmployees" Method="GetCurrentCricketEmployees">
    <ElementType Name="GetCurrentCricketEmployeesResult">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sale_name" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RetireInactiveCricketMembers" Method="RetireInactiveCricketMembers">
    <Parameter Name="IdxCount" Parameter="idxCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RetireInactivePaydayMembers" Method="RetireInactivePaydayMembers">
    <Parameter Name="IdxCount" Parameter="idxCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetActiveMembersForPswdUpdate" Method="GetActiveMembersForPswdUpdate">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="VarChar(256)" />
    <ElementType Name="GetActiveMembersForPswdUpdateResult">
      <Column Name="idx" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AppUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewPassword" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCurrentPaydayEmployees" Method="GetCurrentPaydayEmployees">
    <ElementType Name="GetCurrentPaydayEmployeesResult">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LogMemberManagementAction" Method="LogMemberManagementAction">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="VarChar(125)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertExtendedMemberInfo" Method="InsertExtendedMemberInfo">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="MemberEmail" Parameter="memberEmail" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MemberUserId" Parameter="memberUserId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="StoreId" Parameter="storeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AppUserId" Parameter="appUserId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllUnapprovedMembers" Method="GetAllUnapprovedMembers">
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="GetAllUnapprovedMembersResult">
      <Column Name="rowNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MemberUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordCount" Method="GetRecordCount">
    <Parameter Name="AppName" Parameter="appName" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IsApproved" Parameter="isApproved" Type="System.Int32" DbType="Int" />
    <Parameter Name="RecordCount" Parameter="recordCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetFeatureTree" Method="GetFeatureTree">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="GroupNameId" Parameter="groupNameId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetFeatureTreeResult">
      <Column Name="FeatureCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeatureCategoryName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="FeatureCategoryParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeatureCategorySelected" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupNameId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserInApps" Method="GetUserInApps">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetUserInAppsResult">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSampleData" Method="GetSampleData">
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="GetSampleDataResult">
      <Column Name="rowNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>