#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OttJohnData")]
	public partial class TaskManagerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TaskManagerDataContext() : 
				base("Data Source=.;Initial Catalog=OttJohnData;User ID=sa;Password=3Pitters@3", mappingSource)
		{
			OnCreated();
		}
		
		public TaskManagerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaskManagerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaskManagerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaskManagerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUserTasks")]
		public ISingleResult<GetUserTasksResult> GetUserTasks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<GetUserTasksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RetrieveHealthcareReport")]
		public ISingleResult<RetrieveHealthcareReportResult> RetrieveHealthcareReport()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<RetrieveHealthcareReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubmitTask")]
		public int SubmitTask([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaskId", DbType="Int")] System.Nullable<int> taskId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, taskId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSummaryOfTasks")]
		public ISingleResult<GetSummaryOfTasksResult> GetSummaryOfTasks()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetSummaryOfTasksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRecordCount")]
		public int GetRecordCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppName", DbType="VarChar(30)")] string appName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsApproved", DbType="Int")] System.Nullable<int> isApproved, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecordCount", DbType="Int")] ref System.Nullable<int> recordCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), appName, isApproved, recordCount);
			recordCount = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RetrieveHandbookReport")]
		public ISingleResult<RetrieveHandbookReportResult> RetrieveHandbookReport()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<RetrieveHandbookReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubmitHealthcareElection")]
		public int SubmitHealthcareElection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoursPerWeekThreshhold", DbType="TinyInt")] System.Nullable<byte> hoursPerWeekThreshhold, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Participate", DbType="TinyInt")] System.Nullable<byte> participate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ElectionPlan", DbType="VarChar(25)")] string electionPlan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaskId", DbType="Int")] System.Nullable<int> taskId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaskCompleteId", DbType="Int")] ref System.Nullable<int> taskCompleteId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, hoursPerWeekThreshhold, participate, electionPlan, taskId, taskCompleteId);
			taskCompleteId = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddComment")]
		public int AddComment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserComment", DbType="VarChar(MAX)")] string userComment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArticleNumber", DbType="Int")] System.Nullable<int> articleNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorCode", DbType="Int")] ref System.Nullable<int> errorCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userComment, userId, articleNumber, errorCode);
			errorCode = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ArticleComments")]
		public ISingleResult<ArticleCommentsResult> ArticleComments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArticleNumber", DbType="Int")] System.Nullable<int> articleNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), articleNumber);
			return ((ISingleResult<ArticleCommentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetArticle")]
		public ISingleResult<GetArticleResult> GetArticle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArticleId", DbType="Int")] System.Nullable<int> articleId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), articleId);
			return ((ISingleResult<GetArticleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetArticleSynopsis")]
		public ISingleResult<GetArticleSynopsisResult> GetArticleSynopsis([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryFilter", DbType="VarChar(512)")] string categoryFilter)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryFilter);
			return ((ISingleResult<GetArticleSynopsisResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetVisitCounts")]
		public ISingleResult<GetVisitCountsResult> GetVisitCounts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetVisitCountsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSynopsisRecordCount")]
		public int GetSynopsisRecordCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryFilter", DbType="VarChar(512)")] string categoryFilter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecordCount", DbType="Int")] ref System.Nullable<int> recordCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryFilter, recordCount);
			recordCount = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetArticleSynopsisNew")]
		public ISingleResult<GetArticleSynopsisNewResult> GetArticleSynopsisNew([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrentPage", DbType="Int")] System.Nullable<int> currentPage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryFilter", DbType="VarChar(512)")] string categoryFilter)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageSize, currentPage, categoryFilter);
			return ((ISingleResult<GetArticleSynopsisNewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddFlashCard")]
		public int AddFlashCard([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlashCardQuestion", DbType="VarChar(1024)")] string flashCardQuestion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlashCardAnswer", DbType="VarChar(1024)")] string flashCardAnswer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlashCardCategory", DbType="Int")] System.Nullable<int> flashCardCategory)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), flashCardQuestion, flashCardAnswer, flashCardCategory);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetFlashCard")]
		public ISingleResult<GetFlashCardResult> GetFlashCard([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryIdx", DbType="Int")] System.Nullable<int> categoryIdx, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SelectedCatItem", DbType="Int")] System.Nullable<int> selectedCatItem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryItemsChosen", DbType="VarChar(30)")] string categoryItemsChosen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryIdx, selectedCatItem, categoryItemsChosen);
			return ((ISingleResult<GetFlashCardResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUsedCategories")]
		public ISingleResult<GetUsedCategoriesResult> GetUsedCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsFlashCard", DbType="Int")] System.Nullable<int> isFlashCard)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isFlashCard);
			return ((ISingleResult<GetUsedCategoriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUsedViewCategories")]
		public ISingleResult<GetUsedViewCategoriesResult> GetUsedViewCategories()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetUsedViewCategoriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSpecificCategories")]
		public ISingleResult<GetSpecificCategoriesResult> GetSpecificCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CatList", DbType="VarChar(128)")] string catList)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), catList);
			return ((ISingleResult<GetSpecificCategoriesResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetUserTasksResult
	{
		
		private int _TaskId;
		
		private string _TaskName;
		
		private string _LookupName;
		
		private int _TaskPriorityId;
		
		public GetUserTasksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskId", DbType="Int NOT NULL")]
		public int TaskId
		{
			get
			{
				return this._TaskId;
			}
			set
			{
				if ((this._TaskId != value))
				{
					this._TaskId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string TaskName
		{
			get
			{
				return this._TaskName;
			}
			set
			{
				if ((this._TaskName != value))
				{
					this._TaskName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LookupName", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string LookupName
		{
			get
			{
				return this._LookupName;
			}
			set
			{
				if ((this._LookupName != value))
				{
					this._LookupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskPriorityId", DbType="Int NOT NULL")]
		public int TaskPriorityId
		{
			get
			{
				return this._TaskPriorityId;
			}
			set
			{
				if ((this._TaskPriorityId != value))
				{
					this._TaskPriorityId = value;
				}
			}
		}
	}
	
	public partial class RetrieveHealthcareReportResult
	{
		
		private string _ReportItem;
		
		public RetrieveHealthcareReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportItem", DbType="NVarChar(219)")]
		public string ReportItem
		{
			get
			{
				return this._ReportItem;
			}
			set
			{
				if ((this._ReportItem != value))
				{
					this._ReportItem = value;
				}
			}
		}
	}
	
	public partial class GetSummaryOfTasksResult
	{
		
		private int _id;
		
		private System.Nullable<int> _TaskId;
		
		private string _TaskName;
		
		private System.Nullable<int> _Completed;
		
		private System.Nullable<decimal> _Proportion;
		
		public GetSummaryOfTasksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskId", DbType="Int")]
		public System.Nullable<int> TaskId
		{
			get
			{
				return this._TaskId;
			}
			set
			{
				if ((this._TaskId != value))
				{
					this._TaskId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskName", DbType="VarChar(200)")]
		public string TaskName
		{
			get
			{
				return this._TaskName;
			}
			set
			{
				if ((this._TaskName != value))
				{
					this._TaskName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Completed", DbType="Int")]
		public System.Nullable<int> Completed
		{
			get
			{
				return this._Completed;
			}
			set
			{
				if ((this._Completed != value))
				{
					this._Completed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proportion", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Proportion
		{
			get
			{
				return this._Proportion;
			}
			set
			{
				if ((this._Proportion != value))
				{
					this._Proportion = value;
				}
			}
		}
	}
	
	public partial class RetrieveHandbookReportResult
	{
		
		private string _ReportItem;
		
		public RetrieveHandbookReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportItem", DbType="NVarChar(721)")]
		public string ReportItem
		{
			get
			{
				return this._ReportItem;
			}
			set
			{
				if ((this._ReportItem != value))
				{
					this._ReportItem = value;
				}
			}
		}
	}
	
	public partial class ArticleCommentsResult
	{
		
		private string _content;
		
		private System.Guid _UserId;
		
		private System.Nullable<int> _ArticleNumber;
		
		private string _UserName;
		
		private System.DateTime _DateStamp;
		
		public ArticleCommentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleNumber", DbType="Int")]
		public System.Nullable<int> ArticleNumber
		{
			get
			{
				return this._ArticleNumber;
			}
			set
			{
				if ((this._ArticleNumber != value))
				{
					this._ArticleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStamp", DbType="DateTime NOT NULL")]
		public System.DateTime DateStamp
		{
			get
			{
				return this._DateStamp;
			}
			set
			{
				if ((this._DateStamp != value))
				{
					this._DateStamp = value;
				}
			}
		}
	}
	
	public partial class GetArticleResult
	{
		
		private int _id;
		
		private string _Title;
		
		private string _ContentUrl;
		
		private System.DateTime _DateStamp;
		
		private System.Nullable<int> _ArticleNumber;
		
		public GetArticleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentUrl", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string ContentUrl
		{
			get
			{
				return this._ContentUrl;
			}
			set
			{
				if ((this._ContentUrl != value))
				{
					this._ContentUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStamp", DbType="DateTime NOT NULL")]
		public System.DateTime DateStamp
		{
			get
			{
				return this._DateStamp;
			}
			set
			{
				if ((this._DateStamp != value))
				{
					this._DateStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleNumber", DbType="Int")]
		public System.Nullable<int> ArticleNumber
		{
			get
			{
				return this._ArticleNumber;
			}
			set
			{
				if ((this._ArticleNumber != value))
				{
					this._ArticleNumber = value;
				}
			}
		}
	}
	
	public partial class GetArticleSynopsisResult
	{
		
		private int _id;
		
		private System.Nullable<int> _ArticleNumber;
		
		private string _Title;
		
		private string _synopsis;
		
		private string _Categories;
		
		private System.Nullable<System.DateTime> _DateStamp;
		
		public GetArticleSynopsisResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleNumber", DbType="Int")]
		public System.Nullable<int> ArticleNumber
		{
			get
			{
				return this._ArticleNumber;
			}
			set
			{
				if ((this._ArticleNumber != value))
				{
					this._ArticleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(256)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_synopsis", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string synopsis
		{
			get
			{
				return this._synopsis;
			}
			set
			{
				if ((this._synopsis != value))
				{
					this._synopsis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", DbType="VarChar(1024)")]
		public string Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this._Categories = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateStamp
		{
			get
			{
				return this._DateStamp;
			}
			set
			{
				if ((this._DateStamp != value))
				{
					this._DateStamp = value;
				}
			}
		}
	}
	
	public partial class GetVisitCountsResult
	{
		
		private string _ActivityDate;
		
		private System.Nullable<int> _VisitCount;
		
		public GetVisitCountsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityDate", DbType="VarChar(20)")]
		public string ActivityDate
		{
			get
			{
				return this._ActivityDate;
			}
			set
			{
				if ((this._ActivityDate != value))
				{
					this._ActivityDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitCount", DbType="Int")]
		public System.Nullable<int> VisitCount
		{
			get
			{
				return this._VisitCount;
			}
			set
			{
				if ((this._VisitCount != value))
				{
					this._VisitCount = value;
				}
			}
		}
	}
	
	public partial class GetArticleSynopsisNewResult
	{
		
		private System.Nullable<int> _rowNum;
		
		private System.Nullable<int> _id;
		
		private System.Nullable<int> _ArticleNumber;
		
		private string _Title;
		
		private string _synopsis;
		
		private string _Categories;
		
		private System.Nullable<System.DateTime> _DateStamp;
		
		public GetArticleSynopsisNewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowNum", DbType="Int")]
		public System.Nullable<int> rowNum
		{
			get
			{
				return this._rowNum;
			}
			set
			{
				if ((this._rowNum != value))
				{
					this._rowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleNumber", DbType="Int")]
		public System.Nullable<int> ArticleNumber
		{
			get
			{
				return this._ArticleNumber;
			}
			set
			{
				if ((this._ArticleNumber != value))
				{
					this._ArticleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(256)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_synopsis", DbType="VarChar(4000)")]
		public string synopsis
		{
			get
			{
				return this._synopsis;
			}
			set
			{
				if ((this._synopsis != value))
				{
					this._synopsis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", DbType="VarChar(1024)")]
		public string Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this._Categories = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateStamp
		{
			get
			{
				return this._DateStamp;
			}
			set
			{
				if ((this._DateStamp != value))
				{
					this._DateStamp = value;
				}
			}
		}
	}
	
	public partial class GetFlashCardResult
	{
		
		private string _FlashCardQuestion;
		
		private string _FlashCardAnswer;
		
		public GetFlashCardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlashCardQuestion", DbType="VarChar(1024)")]
		public string FlashCardQuestion
		{
			get
			{
				return this._FlashCardQuestion;
			}
			set
			{
				if ((this._FlashCardQuestion != value))
				{
					this._FlashCardQuestion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlashCardAnswer", DbType="VarChar(1024)")]
		public string FlashCardAnswer
		{
			get
			{
				return this._FlashCardAnswer;
			}
			set
			{
				if ((this._FlashCardAnswer != value))
				{
					this._FlashCardAnswer = value;
				}
			}
		}
	}
	
	public partial class GetUsedCategoriesResult
	{
		
		private int _id;
		
		private string _name;
		
		private string _BackColor;
		
		private string _ForeColor;
		
		public GetUsedCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackColor", DbType="VarChar(20)")]
		public string BackColor
		{
			get
			{
				return this._BackColor;
			}
			set
			{
				if ((this._BackColor != value))
				{
					this._BackColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeColor", DbType="VarChar(20)")]
		public string ForeColor
		{
			get
			{
				return this._ForeColor;
			}
			set
			{
				if ((this._ForeColor != value))
				{
					this._ForeColor = value;
				}
			}
		}
	}
	
	public partial class GetUsedViewCategoriesResult
	{
		
		private int _id;
		
		private string _name;
		
		private string _BackColor;
		
		private string _ForeColor;
		
		private System.Nullable<int> _CardCount;
		
		public GetUsedViewCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackColor", DbType="VarChar(20)")]
		public string BackColor
		{
			get
			{
				return this._BackColor;
			}
			set
			{
				if ((this._BackColor != value))
				{
					this._BackColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeColor", DbType="VarChar(20)")]
		public string ForeColor
		{
			get
			{
				return this._ForeColor;
			}
			set
			{
				if ((this._ForeColor != value))
				{
					this._ForeColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCount", DbType="Int")]
		public System.Nullable<int> CardCount
		{
			get
			{
				return this._CardCount;
			}
			set
			{
				if ((this._CardCount != value))
				{
					this._CardCount = value;
				}
			}
		}
	}
	
	public partial class GetSpecificCategoriesResult
	{
		
		private System.Nullable<int> _id;
		
		private string _name;
		
		private string _BackColor;
		
		private string _ForeColor;
		
		private System.Nullable<int> _CardCount;
		
		public GetSpecificCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(128)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackColor", DbType="VarChar(128)")]
		public string BackColor
		{
			get
			{
				return this._BackColor;
			}
			set
			{
				if ((this._BackColor != value))
				{
					this._BackColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeColor", DbType="VarChar(128)")]
		public string ForeColor
		{
			get
			{
				return this._ForeColor;
			}
			set
			{
				if ((this._ForeColor != value))
				{
					this._ForeColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCount", DbType="Int")]
		public System.Nullable<int> CardCount
		{
			get
			{
				return this._CardCount;
			}
			set
			{
				if ((this._CardCount != value))
				{
					this._CardCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
